config/routes.rb
RecipeCost::Application.routes.draw do
  
  resources :plate_categories

  resources :recipe_components

  resources :recipe_categories

  root :to => 'pages#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  resources :ingredient_categories

  match '/signup',  to: 'users#new'
  match '/sign_in', to: 'sessions#new'
  match '/demo',    to: 'sessions#demo'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/menu', to: 'plates#index'
  match '/inventory', to: 'ingredients#index'
  match '/edit_inventory', to: 'ingredients#edit_inventory'
  match '/edit_prices', to: 'ingredients#edit_prices'
  match '/update_inventory', to: 'ingredients#update_inventory', via: :put
  match '/update_prices', to: 'ingredients#update_prices', via: :put

  resources :plate_ingredients
  resources :plate_components
  resources :plates
  resources :recipe_ingredients
  resources :recipes
  resources :ingredients
  

  

end

app/models/plate.rb
class Plate < ActiveRecord::Base
  attr_accessible :name, :sales_price, :plate_category_id, :user_id

  # Validations
  validates :name, presence: true
  validates :user_id, presence: true
  validates :plate_category_id, presence: true

  # Relationships
  belongs_to :user
  belongs_to :plate_category
  has_many :components, class_name: "PlateComponent", :dependent => :destroy
  has_many :ingredients, class_name: "PlateIngredient", :dependent => :destroy

  # Class instance variables
  @categories = %w(appetizer entree dessert other)
  @units = %w(portion ea oz lb fl_oz cup pint quart Tbsp tsp)

  class << self
  	attr_accessor :categories, :units
  end
  # End of class instance variables

  def total_cost
    ingredients_cost + components_cost
  end

  def food_cost
    cost = self.total_cost
    if self.sales_price
      cost / self.sales_price * 100
    else
      "0"
    end
  end
private
  def ingredients_cost
    cost = 0
    self.ingredients.each do |i|
      cost += i.cost
    end
    cost
  end

  def components_cost
    cost = 0
    self.components.each do |c|
      cost += c.cost(c.recipe)
    end
    cost
  end
end

app/controllers/plates_controller.rb
class PlatesController < ApplicationController
  before_filter :correct_user, only: [:show, :edit, :update, :destroy]

  def index
    redirect_to new_plate_path unless current_user.plates.any?
    @plates = current_user.plates
    @categories = current_user.plate_categories
  end

  def show
    @plate = Plate.find(params[:id])
    @plate_component = PlateComponent.new 
    @plate_ingredient = PlateIngredient.new
    @recipes = current_user.recipes
  end

  def new
    @plate = Plate.new
  end

  def edit
    @plate = Plate.find(params[:id])
  end

  def create
    @plate = Plate.new(params[:plate])

    if @plate.save
      flash[:success] = "Plate was successfully created."
      redirect_to @plate
    else
      render action: "new"
    end
  end

  def update
    @plate = Plate.find(params[:id])

    if @plate.update_attributes(params[:plate])
      flash[:success] = "#{@plate.name} was successfully updated"
      redirect_to @plate
    else
      render action: "edit"
    end
  end

  def destroy
    @plate = Plate.find(params[:id]).destroy
    redirect_to plates_url
  end

private

  def correct_user
    @plate = Plate.find(params[:id])
    redirect_to plates_url unless current_user?(@plate.user)
  end
end

app/views/plates/_form.html.erb
<%= form_for @plate do |f| %>
  
  <% if @plate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plate.errors.count, "error") %> prohibited this plate from being saved:</h2>

      <ul>
      <% @plate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-4">
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :plate_category_id %>
      <%= link_to "(Edit Categories)", plate_categories_path %>

      <%= f.select :plate_category_id, current_user.plate_categories.map{ |c| [c.name, c.id] }, {}, class: "form-control"  %>
    </div>
    <div class="form-group">
      <%= f.label :sales_price %><br />
      <%= f.text_field :sales_price, class: "form-control" %>
    </div>

    <%= f.hidden_field :user_id, value: current_user.id %>

    <div class="actions">
      <%= f.submit class: "btn btn-default" %>
    </div>
  </div>

    
  
<% end %>

app/views/plates/_panel_components.html.erb
<div class="col-md-8">
	<div class="panel panel-primary" id="plate_component_form">
			
		<div class="panel-heading">
      <h3 class="panel-title">Plate Components</h3>
    </div>

    <div class="panel-body">
    	<table class="table">
    	  <thead>
          <tr>
            <th>Amount</th>
            <th>Component</th>
            <th>Cost</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <% @plate.components.each do |component| %>
          <tr>
            <td><%= component.quantity %> <%= component.unit.humanize.downcase %></td>
            <td>

              <%= link_to component.recipe.name, component.recipe, class: "tip", data: {toggle: "tooltip", placement: "right", title: "#{number_to_currency component.recipe.cost_per_unit} / #{component.recipe.yield_unit}"} %>

            </td>
            <td><%= number_to_currency component.cost(component.recipe) %></td>
            <td><%= link_to 'Edit', edit_plate_component_path(component) %></td>
            <td><%= link_to 'Delete', component, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
    	</table>	

    	<%= render "plate_components/form" %>

    	<%= link_to "Add Component", "#", { class: "btn btn-primary", id: "add_component" } %>

    </div>
	</div>
</div>

app/views/plates/_panel_ingredients.html.erb
<div class="col-md-4"></div>
<div class="col-md-8">
	<div class="panel panel-success" id="plate_ingredients_form">
			
		<div class="panel-heading">
      <h3 class="panel-title">Ingredients &amp; Extras</h3>
    </div>

    <div class="panel-body">
    	<table class="table">
    	  <thead>
          <tr>
            <th>Amount</th>
            <th>Ingredient</th>
            <th>Cost</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <% @plate.ingredients.each do |ingredient| %>
          <tr>
            <td><%= ingredient.quantity %> <%= ingredient.unit %></td>

            <td>
                
                <%= link_to ingredient.ingredient.name, edit_ingredient_path(ingredient.ingredient), class: "tip", data: {toggle: "tooltip", placement: "right", title: "#{number_to_currency ingredient.ingredient.price} / #{ingredient.ingredient.unit}"} %>
            </td>

            <td><%= number_to_currency ingredient.cost %></td>
            <td><%= link_to 'Edit', edit_plate_ingredient_path(ingredient) %></td>
            <td><%= link_to 'Delete', ingredient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
    	</table>	

    	<%= render "plate_ingredients/form" %>

    	<%= link_to "Add Ingredient", "#", { class: "btn btn-success", id: "add_ingredient" } %>

    </div>
	</div>
</div>

app/views/plates/_stats.html.erb
<div class="col-md-4">
	<p class="text-muted">
		<b><%= "Sales Price".upcase %></b>
	</p>

	<% if @plate.sales_price %>
		<p class="jumbo_text"><%= number_to_currency @plate.sales_price %></p>
	<% else %>
		<p class="jumbo_text">$0.00</p>
	<% end %>

	<p class="text-muted">
		<b><%= "Cost".upcase %></b>
	</p>

	<p class="jumbo_text"><%= number_to_currency @plate.total_cost %></p>

	<p class="text-muted">
		<b><%= "Food Cost".upcase %></b>
	</p>

	<p class="jumbo_text"><%= number_to_percentage @plate.food_cost %></p>

	<%= link_to 'Edit', edit_plate_path(@plate), class: "btn btn-default" %> 

</div>

app/views/plates/edit.html.erb
<h1 class="page-header">Editing plate</h1>

<div class="row">
	<%= render 'form' %>
</div>

app/views/plates/index.html.erb
<section class="col-sm-4 category color color-plate">
  <h1 class="page-header">Menu Items</h1>
  <% @categories.each do |category| %>
    <a id="<%= category.name %>" href="#"><%= category.name %></a>
  <% end %>
  <hr>
  <a id="add" href="/plate_categories">
    Add Category
    <span class="glyphicon glyphicon-th-list"></span>
  </a>
</section>

<section id="resources" class="col-sm-8">
  <table class="table">
    <thead>
    <tr>
      <th>Name</th>
      <th>Cost</th>
      <th>Sales price</th>
      <th>Food Cost %</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <% @plates.each do |plate| %>
  <tr data-category="<%= plate.plate_category.name %>" class="resource">
    <td><%= link_to plate.name, plate_path(plate) %></td>
    <td><%= number_to_currency plate.total_cost %></td>
    <td><%= number_to_currency plate.sales_price %></td>
    <td><%= number_to_percentage plate.food_cost %></td>
    <td><%= link_to 'Show', plate_path(plate) %></td>
    <td><%= link_to 'Delete', plate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

  </table>
  <%= link_to 'New Plate', new_plate_path, class: "btn btn-default" %>
</section>

app/views/plates/new.html.erb
<section class="color color-plate col-sm-4">
  <h1 class="page-header">New Menu Item</h1>
  <aside id="tip">
  	<span class="glyphicon glyphicon-star"></span>
    <h5>Tip</h5>
    <p>If there are different types of same ingredient you can use a dash to specify a more descriptive name.</p>
    <h5>Examples</h5>
    <ul>
    	<li>Onion - Yellow</li>
    	<li>Onion - Red</li>
    	<li>Flour - AP</li>
    	<li>Flour - Bread</li>
    </ul>

  </aside>
</section>

<section id="resources" class="col-sm-8">
	<div class="row">
		<%= render 'form' %>
	</div>
</section>

app/views/plates/show.html.erb
<h1 class="page-header"><%= @plate.name %> <small>(<%= @plate.plate_category.name %>)</small></h1>

<div class="row">
	<%= render "stats" %>
	<%= render "panel_components" %>
	<%= render "panel_ingredients" %>
</div>