config/routes.rb
RecipeCost::Application.routes.draw do
  
  resources :plate_categories

  resources :recipe_components

  resources :recipe_categories

  root :to => 'pages#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  resources :ingredient_categories

  match '/signup',  to: 'users#new'
  match '/sign_in', to: 'sessions#new'
  match '/demo',    to: 'sessions#demo'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/menu', to: 'plates#index'
  match '/inventory', to: 'ingredients#index'
  match '/edit_inventory', to: 'ingredients#edit_inventory'
  match '/edit_prices', to: 'ingredients#edit_prices'
  match '/update_inventory', to: 'ingredients#update_inventory', via: :put
  match '/update_prices', to: 'ingredients#update_prices', via: :put

  resources :plate_ingredients
  resources :plate_components
  resources :plates
  resources :recipe_ingredients
  resources :recipes
  resources :ingredients
  

  

end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :name, :yield, :yield_unit, :recipe_category_id

  # Validations
  validates :name, presence: true
  validates :user_id, presence: true
  validates :recipe_category_id, presence: true

  # Relationships
  belongs_to :user
  belongs_to :recipe_category		  				
  has_many :ingredients, class_name: "RecipeIngredient",:dependent => :destroy
  has_many :components,  class_name: "RecipeComponent", :dependent => :destroy

  default_scope order: :name

  # Class instance variables
  @categories = %w(sauces stocks salads proteins other).sort
  @units = %w(portion ea oz lb fl_oz cup pint quart gallon Tbsp tsp)

  class << self
  	attr_accessor :categories, :units
  end
  # End of class instance variables

  def total_cost
  	ingredients_cost + components_cost
  end

  def ingredients_cost
    t_cost = 0
    self.ingredients.each do |i|
      t_cost += i.cost
    end
    t_cost
  end

  def components_cost
    t_cost = 0
    self.components.each do |c|
      t_cost += c.cost(c.component)
    end
    t_cost
  end

  def cost_per_unit
    total_cost / self.yield if self.yield
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  
  before_filter :correct_user, only: [:show, :edit, :update, :destroy]

  def index
    redirect_to new_recipe_path unless current_user.recipes.any?
    @recipes = current_user.recipes.includes(ingredients: :ingredient).all
    @categories = current_user.recipe_categories
  end

  def show
    @recipe = Recipe.find(params[:id])
    @ingredients = current_user.ingredients
    @ingredient = RecipeIngredient.new
    @recipe_component = RecipeComponent.new
    @recipes = current_user.recipes.to_a - [@recipe]
  end

  def new
    @recipe = Recipe.new
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def create
    @recipe = current_user.recipes.build(params[:recipe])

    if @recipe.save
      flash[:success] = @recipe.name + ' Recipe was successfully created.'
      redirect_to @recipe
    else
      render action: "new"
    end
  end

  def update
    @recipe = Recipe.find(params[:id])

    respond_to do |format|
      if @recipe.update_attributes(params[:recipe])
        flash[:success] = @recipe.name + ' Recipe was successfully updated.'
        format.html { redirect_to @recipe }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @recipe = Recipe.find(params[:id]).destroy
    redirect_to recipes_url
  end

private

  def correct_user
    @recipe = Recipe.find(params[:id])
    redirect_to root_path unless current_user?(@recipe.user)
  end
end

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>

  <div class="col-md-4">

    <%= render "shared/error_messages", object: @recipe %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :recipe_category_id, "Category" %>
      <%= link_to "(Edit Categories)", recipe_categories_path %>

      <%= f.select :recipe_category_id, current_user.recipe_categories.map{ |c| [c.name, c.id] }, {}, class: "form-control"  %>
    </div>
    
    <!-- ********** Yield Input ********** -->
    <div class="row">
      <div class="form-group col-md-4">
        <%= f.label :yield, "Total Yield" %>
        <%= f.text_field :yield, class: "form-control" %>
      </div>
      <div class="form-group col-md-4">
        <%= f.label :yield_unit, "Unit" %>
        <select class="form-control" id="recipe_yiled_unit" name="recipe[yield_unit]">
          <!-- <option value></option> -->
          <%= Recipe.units.each do |unit| %>

            <% if @recipe.yield_unit == unit %>
              <option selected="selected" value="<%= unit %>"><%= unit.humanize.downcase %></option>
            <% else %>
              <option value="<%= unit %>"><%= unit.humanize.downcase %></option>
            <% end %>
          <% end %>
        </select>
      </div>
    </div>
    <!-- ********** End Yield Input ********** -->


    <hr>
    <div class="actions">
      <%= f.submit class: "btn btn-default " %>
    </div>

  </div>
  
<% end %>

app/views/recipes/_panel_components.html.erb
<div class="panel panel-primary" id="recipe_component_form">
  <div class="panel-heading">
    <h3 class="panel-title">Components</h3>
  </div>

  <div class="panel-body">
  	<table class="table">
  	  <thead>
        <tr>
          <th>Amount</th>
          <th>Component</th>
          <th>Cost</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <% @recipe.components.each do |rc| %>
        <% c = rc.component %>
        <tr>
          <td><%= rc.quantity %> <%= rc.unit %></td>
          <td>

            <%= link_to c.name, c, class: "tip", data: {toggle: "tooltip", placement: "right", title: "#{number_to_currency(c.total_cost / c.yield)} / #{c.yield_unit}"} %>

          </td>
          <td><%= number_to_currency rc.cost(rc.component) %></td>
          <td><%= link_to 'Edit', edit_recipe_component_path(rc) %></td>
          <td><%= link_to 'Delete', rc, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
  	</table>	

  	<%= render "recipe_components/form" %>

  	<%= link_to "Add Component", "#", { class: "btn btn-primary", id: "add_component" } %>
  </div>
</div>

app/views/recipes/_panel_ingredients.html.erb
<div class="panel panel-success" id="recipes_ingredient_form">
	<div class="panel-heading">
    <h3 class="panel-title">Ingredients</h3>
  </div>
  <div class="panel-body" id="recipe_ingredients_form">
  	<table class="table">
      <thead>
        <tr>
          <th>Amount</th>
          <th>Ingredient</th>
          <th>Cost</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <% @recipe.ingredients.each do |i| %>
        
        <tr>
          <td><%= i.quantity %> <%= i.unit %></td>
          <td>

            <% unless i.ingredient.yield %>
              <% @tooltip = "#{number_to_currency i.ingredient.price} / #{i.ingredient.unit}" %>
            <% else %>
              <% @tooltip = "#{number_to_currency i.ingredient.price} / #{i.ingredient.unit}, EP: #{i.ingredient.yield.to_i}%" %>
            <% end %>

            <%= link_to i.ingredient.name, edit_ingredient_path(i.ingredient), class: "tip", data: {toggle: "tooltip", placement: "top", title: "#{@tooltip}"} %>

          </td>
          <td><%= number_to_currency i.cost %></td>
          <td><%= link_to "Edit", edit_recipe_ingredient_path(i) %></td>
          <td><%= link_to "Delete", i, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </table>
    <%= render "recipe_ingredients/form" %>

    <%= link_to "Add Ingredient", "#", { class: "btn btn-success", id: "add_ingredient" } %>
  </div>
</div>

app/views/recipes/_stats.html.erb
<!-- ********** Cost ********** -->
<section id="stats">
  <p class="text-muted"><%= "Total cost".upcase %></p>
  <p class="jumbo_text"><%= number_to_currency @recipe.total_cost %></p>

  <p class="text-muted"><%= "Total Yield".upcase %></p>
  <% if @recipe.yield %>
    <% y = @recipe.yield.to_s.gsub(/\.0$/, "") %>
    <p class="jumbo_text"><%= pluralize( y, @recipe.yield_unit.humanize.downcase) %></p>
  <% else %>
    <p class="jumbo_text">-</p>
  <% end %>

  <p class="text-muted"><%= "Cost per #{@recipe.yield_unit.humanize.downcase}".upcase %></p>
  <% if @recipe.yield %>
    <p class="jumbo_text"><%= number_to_currency @recipe.cost_per_unit %></p>
  <% else %>
    <p class="jumbo_text">-</p>
  <% end %>
</section>

  



  

app/views/recipes/edit.html.erb
<h1 class="page-header">Editing recipe</h1>

<div class="row">
	<%= render 'form' %>
</div>

app/views/recipes/index.html.erb
<section class="col-sm-4 color category color-recipe">
  <h1 class="page-header">Recipes</h1>
  <% @categories.each do |category| %>
    <a id="<%= category.name %>" href="#"><%= category.name %></a>
  <% end %>
  <hr>
  <a id="add" href="/recipe_categories">
    Add Category
    <span class="glyphicon glyphicon-th-list"></span>
  </a>

</section>

<section id="resources" class="col-sm-8">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Total Yield</th>
        <th>Category</th>
        <th>Total Cost</th>
        <th>Cost per Unit</th>
        <th></th>
      </tr>
    </thead>

    <% @recipes.each do |recipe| %>
      <tr data-category="<%= recipe.recipe_category.name %>" class="resource">
        <td><%= link_to recipe.name, recipe_path(recipe) %></td>

        <% if recipe.yield %>
          <td><%= recipe.yield %> <%= recipe.yield_unit.humanize.downcase %></td>
        <% else %>
          <td>-</td>
        <% end %>

        <td><%= recipe.recipe_category.name %></td>
        <td><%= number_to_currency recipe.total_cost %></td>
        <td><%= number_to_currency recipe.cost_per_unit %></td>
        <td><%= link_to 'Delete', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </table>
  <%= link_to 'New Recipe', new_recipe_path, class: "btn btn-default" %>
</section>

app/views/recipes/new.html.erb
<div class="container">
	<h1 class="page-header">New recipe</h1>


	<div class="row">
		<%= render 'form' %>
	</div>

</div>

app/views/recipes/show.html.erb
<section class="col-sm-4 color color-recipe">
  <h1 class="page-header"><%= @recipe.name %></h1>
  <%= render "stats" %>
  <hr>
  <a id="add" href="<%= edit_recipe_path(@recipe) %>">
  	<span class="glyphicon glyphicon-edit"></span>
    Edit Recipe
    <!-- <span class="glyphicon glyphicon-edit"></span> -->
  </a>
</section>

<section id="resources" class="col-sm-8">
  <%= render "panel_ingredients" %>
  <%= render "panel_components" %>
</section>