config/routes.rb
RecipeCost::Application.routes.draw do
  
  resources :plate_categories

  resources :recipe_components

  resources :recipe_categories

  root :to => 'pages#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  resources :ingredient_categories

  match '/signup',  to: 'users#new'
  match '/sign_in', to: 'sessions#new'
  match '/demo',    to: 'sessions#demo'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/menu', to: 'plates#index'
  match '/inventory', to: 'ingredients#index'
  match '/edit_inventory', to: 'ingredients#edit_inventory'
  match '/edit_prices', to: 'ingredients#edit_prices'
  match '/update_inventory', to: 'ingredients#update_inventory', via: :put
  match '/update_prices', to: 'ingredients#update_prices', via: :put

  resources :plate_ingredients
  resources :plate_components
  resources :plates
  resources :recipe_ingredients
  resources :recipes
  resources :ingredients
  

  

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  
  attr_accessible :name, :ingredient_category_id, :price,  
                  :unit, :yield, :ounces_per_cup, :inventory
                  # :purveyor, :storage
  # Validations
  validates :name, presence: true
  validates :user_id, presence: true

  # Relationships
  belongs_to :user
  belongs_to :ingredient_category
  has_many :recipe_ingredients, :dependent => :destroy
  has_many :plate_ingredients, :dependent => :destroy
  
  default_scope order("name, ingredient_category_id")							

  # Class instance variables
  @categories = %w(dairy vegetables meats fruits spices other).sort

  @units = %w(oz lb fl_oz cup pint quart gallon Tbsp tsp ea pack head can bunch)
  
  class << self
  	attr_accessor :categories, :units
  end
  # End of class instance variables

  def inventory_cost
    self.inventory.to_i * price
  end

end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_filter :correct_user, only: [:show, :edit, :update, :destroy]

  def index
    if signed_in?
      redirect_to new_ingredient_path unless current_user.ingredients.any?
      @ingredients = current_user.ingredients
      @categories = current_user.ingredient_categories
      @total_inventory = 0
      @ingredients.each do |i|
        @total_inventory += i.inventory_cost if i.inventory_cost
      end
    else
      redirect_to root_path
    end
  end

  def new
    @ingredient = Ingredient.new

    if params[:category]
      @ingredient.ingredient_category_id = params[:category]
    end
  end

  def edit
  end

  def create
    @ingredient = current_user.ingredients.build(params[:ingredient])

    @ingredient.name = params[:ingredient][:name].titleize

    if @ingredient.save
      flash[:success] = @ingredient.name + " was successfully added to ingredients."
      redirect_to ingredients_path
    else
      render action: "new"
    end
    
  end

  def update
    if @ingredient.update_attributes(params[:ingredient])
      flash[:success] = @ingredient.name + " has been successfully updated!"
      redirect_to ingredients_path
    else
      render action: "edit"
    end
  end

  def destroy
    @ingredient.destroy
    redirect_to ingredients_url
  end

  def edit_prices
    if signed_in?
      @ingredients = current_user.ingredients
      @categories = current_user.ingredient_categories
    else
      redirect_to root_path
    end
  end

  def update_prices
    @ingredients = Ingredient.update(params[:ingredients].keys, params[:ingredients].values)
    flash[:success] = "Prices Updated successfully"
    render "edit_prices"
  end

  def edit_inventory
    if signed_in?
      @ingredients = current_user.ingredients
      @categories = current_user.ingredient_categories
    else
      redirect_to root_path
    end
  end

  def update_inventory

  end

private

  def correct_user
    @ingredient = Ingredient.find(params[:id])
    redirect_to root_path unless current_user?(@ingredient.user)
  end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
	 def cost
    ing = self.ingredient

    same_units = self.ingredient.unit == self.unit && ing.price? && self.quantity?
    weight_units = weight_unit?(ing.unit) && weight_unit?(self.unit) 
    volume_units = volume_unit?(ing.unit) && volume_unit?(self.unit)
    
    if same_units
      cost_same_units(q_yield, ing.price)
    elsif weight_units
      cost_weight_units(q_yield, self.unit, ing.price, ing.unit)  
    elsif volume_units
      cost_volume_units(self.quantity, self.unit, ing.price, ing.unit) 
    elsif ing.ounces_per_cup
      cost_unit_mixture(self.q_yield, self.unit, ing.price, ing.unit, ing.ounces_per_cup)
    else
      0
    end
  end

  def q_yield
    self.ingredient.yield ||= 100
    self.quantity / (self.ingredient.yield / 100) if self.quantity?
  end
end

app/views/ingredients/_form.html.erb
<%= form_for @ingredient do |f| %>
  
  <%= render "shared/error_messages", object: @ingredient %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :ingredient_category_id, "Category" %>
    <%= link_to "(Edit Categories)", ingredient_categories_path %>

    <%= f.select :ingredient_category_id, current_user.ingredient_categories.map{ |c| [c.name, c.id] }, {}, class: "form-control"  %>
  </div>

  <hr>
  
  <!-- ********** Price per Unit Input ********** -->
  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :price, "Price" %>
      <%= f.text_field :price, class: "form-control" %>
    </div>
    
    <div class="form-group col-md-8">
      <%= f.label :unit, "per Unit" %>
      <select class="form-control" id="ingredient_unit" name="ingredient[unit]">
        <option></option>
        <%= Ingredient.units.each do |unit| %>
          <% if @ingredient.unit == unit %>
            <option value="<%= unit %>" selected="selected"><%= unit.humanize.downcase %></option>
          <% else %>
            <option value="<%= unit %>"><%= unit.humanize.downcase %></option>
          <% end %>
        <% end %>
      </select>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-4">
      <%= f.label :inventory %>
    <%= f.text_field :inventory, class: "form-control" %>
    </div>
  </div>


  <!-- ********** End Price Input ********** -->

  <hr>

  <div class="form-group">
    <%= f.label :yield, "Yield % (Edible Portion)" %>
    <%= f.text_field :yield, class: "form-control", placeholder: "optional (default is 100)" %>
  </div>

  <div class="form-group">
    <%= f.label :ounces_per_cup, "Ounces per Cup (weight)" %>
    <%= f.text_field :ounces_per_cup, class: "form-control", placeholder: "optional" %>
  </div>

  <!-- <div class="form-group">
    <%= f.label :purveyor %>
    <select class="form-control" id="ingredient_purveyor" name="ingredient[purveyor]">
      <%= %w(store_1 store_2 store_3).each do |p| %>
        <% if @ingredient.purveyor == p %>
          <option selected="selected"><%= p.titleize %></option>
        <% else %>
          <option><%= p.titleize %></option>
        <% end %>
      <% end %>
    </select>
  </div> -->

  <!-- <div class="form-group">
    <%= f.label :inventory %>
    <%= f.text_field :inventory, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :storage %>
    <select class="form-control" id="ingredient_storage" name="ingredient[storage]">
      <%= %w(walk-in freezer reach-in pantry).each do |s| %>
        <% if @ingredient.purveyor == s %>
          <option selected="selected"><%= s.humanize.downcase %></option>
        <% else %>
          <option><%= s.humanize.downcase %></option>
        <% end %>
      <% end %>
    </select>
  </div> -->
  <hr>
  
    <%= f.submit class: "btn btn-default" %>
  
<% end %>

app/views/ingredients/edit.html.erb
<section class="color color-ingredient col-sm-4">
  <h1 class="page-header"><%= @ingredient.name %></h1>

  <a id="add" href="<%= ingredient_path(@ingredient) %>" data-confirm="Are you sure?" data-method="delete" rel="nofollow">
  	<!-- <span class="glyphicon glyphicon-edit"></span> -->
    Delete Ingredient
    <span class="glyphicon glyphicon-trash"></span>
  </a>
</section>

<section id="resources" class="col-sm-8">
<div class="row">
	<div class="col-md-6">
		<%= render 'form' %>
	</div>
</div>
</section>

app/views/ingredients/edit_inventory.html.erb
<h1 class="page-header">Edit Inventory</h1>


<%= form_tag update_inventory_path, method: :put do %>
  <% @ingredients.each do |ingredient| %>
  	<div class="row">
      <p class="col-md-3" style="display:inline"><%= ingredient.name %> (<%= ingredient.unit %>)</p>
		  <%= fields_for "ingredients[]", ingredient do |f| %>
			  <div class="col-md-4">
			  <%= f.text_field :price, class: "form-control" %>
				</div>
			<% end %>
		</div>
  <% end %>
  <%= submit_tag "Update", class: "btn btn-success" %></td>
<% end %>






      

  
  

app/views/ingredients/edit_prices.html.erb
<h1 class="page-header">Update Prices</h1>

<%= form_tag update_prices_path, method: :put do %>
  <% @ingredients.each do |ingredient| %>
  	<div class="row">
      <p class="col-md-3" style="display:inline; text-align:right"><%= ingredient.name %> (<%= ingredient.unit %>)</p>
		  <%= fields_for "ingredients[]", ingredient do |f| %>
			  <div class="col-md-1">
			  <%= f.text_field :price, class: "form-control" %>
				</div>
			<% end %>
		</div>
  <% end %>
  <%= submit_tag "Update", class: "btn btn-success" %></td>
<% end %>

app/views/ingredients/index.html.erb
<section class="col-sm-4 color category color-ingredient">
  <h1 class="page-header">Inventory</h1>
  <% @categories.each do |category| %>
    <a id="<%= category.name %>" href="#"><%= category.name %></a>
  <% end %>
  <hr>
  <a id="add" href="/ingredient_categories">
    Add Category
    <span class="glyphicon glyphicon-th-list"></span>
  </a>

  <h1><%= @total_inventory %><h1>
</section>

<section id="resources" class="col-sm-8">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "alert alert-#{key}", id: "flash") %>
  <% end %>
  <table class="table table-striped">
    <thead> 
      <tr>
        <th>Name</th>
        <th>Price / Unit</th>
        <th class="hidden-xs">Yield</th>
        <th class="hidden-xs">Oz/Cup</th>
        <th class="hidden-xs">Inventory</th>
        <th class="hidden-xs">Inventory Cost</th>
      </tr>
    </thead>
    
    <% @ingredients.each do |ingredient| %>
                  
      <tr data-category="<%= ingredient.ingredient_category.name %>" class="resource">
        <td><%= link_to ingredient.name, edit_ingredient_path(ingredient) %></td>

        <% if ingredient.price %>
          <td><%= number_to_currency(ingredient.price) %> / <%= ingredient.unit.humanize.downcase %></td>
        <% else %>
          <td>-</td>
        <% end %>

        <% if ingredient.yield %>
          <td class="hidden-xs"><%= number_to_percentage(ingredient.yield, options = { precision: 0}) %></td>
        <% else %>
          <td class="hidden-xs">100%</td>
        <% end %>
        
        <% if ingredient.ounces_per_cup %>
          <td class="hidden-xs"><%= ingredient.ounces_per_cup %> oz</td>
        <% else %>
          <td class="hidden-xs">-</td>
        <% end %>

        <td class="hidden-xs"><%= ingredient.inventory %> <%=ingredient.unit.humanize.downcase if ingredient.inventory %></td>

        <td class="hidden-xs"><%= number_to_currency(ingredient.inventory_cost) if ingredient.inventory %></td>
      </tr>

    <% end %>

  </table>

  <%= link_to "Add Ingredient", "/ingredients/new", class: "btn btn-default" %>

</section>

app/views/ingredients/new.html.erb
<section class="color color-ingredient col-sm-4">
  <h1 class="page-header">New ingredient</h1>
  <aside id="tip">
  	<span class="glyphicon glyphicon-star"></span>
    <h5>Tip</h5>
    <p>If there are different types of same ingredient you can use a dash to specify a more descriptive name.</p>
    <h5>Examples</h5>
    <ul>
    	<li>Onion - Yellow</li>
    	<li>Onion - Red</li>
    	<li>Flour - AP</li>
    	<li>Flour - Bread</li>
    </ul>

  </aside>
</section>

<section id="resources" class="col-sm-8">
	<div class="row">
		<div class="col-md-6">
			<%= render 'form' %>
		</div>
	</div>
</section>

<%= javascript_include_tag "ingredient" %>