config/routes.rb
RecipeCost::Application.routes.draw do
  
  resources :plate_categories

  resources :recipe_components

  resources :recipe_categories

  root :to => 'pages#index'
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  resources :ingredient_categories

  match '/signup',  to: 'users#new'
  match '/sign_in', to: 'sessions#new'
  match '/demo',    to: 'sessions#demo'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/menu', to: 'plates#index'
  match '/inventory', to: 'ingredients#index'
  match '/edit_inventory', to: 'ingredients#edit_inventory'
  match '/edit_prices', to: 'ingredients#edit_prices'
  match '/update_inventory', to: 'ingredients#update_inventory', via: :put
  match '/update_prices', to: 'ingredients#update_prices', via: :put

  resources :plate_ingredients
  resources :plate_components
  resources :plates
  resources :recipe_ingredients
  resources :recipes
  resources :ingredients
  

  

end

app/models/ingredient_category.rb
class IngredientCategory < ActiveRecord::Base
  attr_accessible :name
  belongs_to :user
  has_many :ingredients

  # Validations
  validates :name, presence: true
  validates :user_id, presence: true

  default_scope order(:name)
end

app/controllers/ingredient_categories_controller.rb
class IngredientCategoriesController < ApplicationController
  before_filter :correct_user, only: [:edit, :update, :destroy]
  
  def index
    @ingredient_categories = current_user.ingredient_categories
    @ingredient_category = IngredientCategory.new
  end

  def edit
    @ingredient_category = IngredientCategory.find(params[:id])
  end

  def create
    @ingredient_category = current_user.ingredient_categories.build(params[:ingredient_category])

    if @ingredient_category.save
      flash[:success] = 'Category was added successfully.'
      redirect_to new_ingredient_path
    else
      redirect_to ingredient_categories_path
    end
  end

  def update
    @ingredient_category = IngredientCategory.find(params[:id])

    if @ingredient_category.update_attributes(params[:ingredient_category])
      flash[:success] = 'Category was successfully updated.'
      redirect_to ingredient_categories_path
    else
      render action: "edit"
    end
  end

  def destroy
    @ingredient_category = IngredientCategory.find(params[:id]).destroy
    redirect_to ingredient_categories_url
  end

private

  def correct_user
    @ingredient_category = IngredientCategory.find(params[:id])
    redirect_to root_path unless current_user?(@ingredient_category.user)
  end
end

app/views/ingredient_categories/_form.html.erb
<%= form_for(@ingredient_category) do |f| %>
  <% if @ingredient_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient_category.errors.count, "error") %> prohibited this ingredient_category from being saved:</h2>

      <ul>
      <% @ingredient_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <% if @ingredient_category.name %>
      <%= f.submit "Edit Category", class: "btn btn-default" %>
    <% else %>
      <%= f.submit "Add Category", class: "btn btn-default" %>
    <% end %>
  </div>
<% end %>

app/views/ingredient_categories/edit.html.erb
<h1>Editing Category</h1>
<div class="row">
	<div class="col-md-4">
		<%= render 'form' %>
	</div>
</div>

app/views/ingredient_categories/index.html.erb
<section class="color color-ingredient col-sm-4">
  <h1 class="page-header">Ingredient Categories</h1>
  <aside id="tip">
    <span class="glyphicon glyphicon-star"></span>
    <h5>Examples</h5>
    <p>(Dry, Pantry)</p>
  </aside> 
</section>

<section id="resources" class="col-sm-8">

  <div class="col-md-4">
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th></th>
          <th></th>
        </tr>
      </thead>

    <% @ingredient_categories.each do |ingredient_category| %>
      <tr>
        <td><%= ingredient_category.name %></td>
        <td><%= link_to 'Edit', edit_ingredient_category_path(ingredient_category) %></td>
        <td><%= link_to 'Delete', ingredient_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </table>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">New Category</div>
      <div class="panel-body">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</section>